# Site settings
title: TempoIQ API Documentation
email: support@tempoiq.com
description: > # this means to ignore newlines until "baseurl:"
  Documentation for TempoIQ's APIs. 
baseurl: "/tempo-api-docs"
#url: "http://docs.tempoiq.com" # the base hostname & protocol for your site
twitter_username: tempo_iq
github_username:  TempoIQ
gems:
  - jekyll-redirect-from

# Build settings
markdown: kramdown
highlighter: pygments
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
